baseurl = "https://rimonmostafiz.com/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Rimon Mostafiz"
title = "Rimon's Weblog"
disqusShortname = "rimonmostafiz"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Yet Another Phony Software Engineer"
copyright = "Copyright Â© 2018 Rimon Mostafiz"
logofile = "img/logo.jpg"
faviconfile = "img/favicon.png"
highlightjs = true
progressively = true
align_left = true
lang = "en"

github = "rimonmostafiz"
email = "ferary.rimon@gmail.com"
linkedin = "rimonmostafiz"
twitter = "rimonmostafiz"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false
latestpostcount = 5
